[package]
name = "contest_prep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features= ["derive"]}
text_io = "0.1.12"
is_empty = "0.2.0"